apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - flux-system
  - storageclass_all.yaml
  - ../../infrastructure
  - envoy-gateway-ks.yaml
  - cert-manager-ks.yaml
  - envoy-gateway-proxy-ks.yaml
  - apps-ks.yaml
  - cert-manager-issuers-ks.yaml
