apiVersion: v1
kind: Secret
metadata:
    name: contact-service-secrets
    namespace: contact
type: Opaque
stringData:
    GATEWAY_API_TOKEN: ENC[AES256_GCM,data:W1mVEdS0TjOjoJZr3RPU+iZQD7jYsRUyoGUne+4ELiI5ckXIy1myIFd21LafIRvzeMdiyn25u5IM3LPTP4usfA==,iv:RrZjUnDU3fxQGBCOVgSl4x6idhL4EF7MbIZWGsEl0Zo=,tag:ln8httsWWslTl6PEgrnBRg==,type:str]
    MAILERSEND_TOKEN: ENC[AES256_GCM,data:iycApNbaJmUdNRk0J1oMauzmTLXxxI59N65rID2E2r+sO5ZfV4XXu9zG0FhqLs3rEEkwRI/R0pi2e2alLckfB74neGDt,iv:hTIJaWTbjlQIn+h+KhYpm2M5mxdW8PMS3PtNLOUnTtk=,tag:2LESBvzxqJOqkFX2kBSNIg==,type:str]
sops:
    age:
        - recipient: age19fmyfyqqx37raywwtlt7ynpgq7jd8dq365m79lqe7u8jy7e8kqesk0tzrp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRFA0YTBIUUFXTEIydVdP
            cjQ4L2d0T2VjaFN1Skg1SFVsMXhUdzZsVndjClMxVGdTcVF0MStmNHgyZElsRHZk
            MnI5cWx5TTNMR0NVOGV2d3hoaHRybnMKLS0tIERrWHJmNXIxUnZ3VDMreGxxZVps
            YytFSmVwNVBQSysrMUNIOUlXRC9GL2MKjhlCL2CryVdpD6CzaJTxfXCGJaEO3E2M
            Sgm2HCpqJIjUDN4scL70oHDkwEZXHCIJIy5zwewmLZtV1fXnh47fcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T00:00:52Z"
    mac: ENC[AES256_GCM,data:snNorDu412h2V1/dV4ez+x/tLPn70Nn+VuXkq8MJBAL0CpVZgVCwFb4y62n4b/z0e/rI5kxZu28/dIJm7GPBW2UxDxR5OGjHYxpqoFnZ0hSxDF0O+GfnitxBQuL/ohp2l88F3uHaa0znw/AcxTnq4+mLnkJGzDBDPdyTVABQlj8=,iv:iufnqNG+z9PwoHiLDQankhJelRChd0VtEuZS9pPtEsI=,tag:/2+Qx5jDuzT2xcaMXJnvvg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
