apiVersion: v1
kind: Secret
metadata:
    name: jonathan-github-token
    namespace: jonathan
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:oXwzRfBSmhooO4npslTBKufAv5wVgB9Q9Qt2+UUb9JixHG+wCjrPWMpaflWHRVG1c5UXIW/MIJlea6muhvrC8tpJ/vO+5jv6bUpMcqY9K4DcrOR/Osi0T5f0RnKt,iv:px3nSkapzw/tAAHE6JccaPxVcj8VNR6VTEWEtpWWOek=,tag:llsSSTX/Vl4tIbYdXobthg==,type:str]
sops:
    age:
        - recipient: age19fmyfyqqx37raywwtlt7ynpgq7jd8dq365m79lqe7u8jy7e8kqesk0tzrp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkaW9WeVdnTFc1STEzVnN5
            MG4zNjdadzBMT1lUSjZqZS9VZmt2TUhCV3prCmsxMm1hT0M0QVpYcm1KN01XT3hC
            T084dzRaQUdsMWxVTEwvdHdjUTBFb28KLS0tIC9yWWlpNnJwajVUMTJlZ1E4NSsz
            RzRrK3d5VDZZY2Y5QTdyZjJoL2xkaVkKwljtmSUueDZfxm57WkdCzRbylHOcqDWf
            gbq1W32ciKmiwAGunMS8z3p7BSv8lo/D8cooS4xL/+GNXcnEdBhrlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T20:28:12Z"
    mac: ENC[AES256_GCM,data:DGjycJCT8Ni4CU+sC4a9jz1V8WMSMoAffZRWrHKqMFrKDz9z0Dc19Zy9i/ZMd0sZR7D20C/grbnZK1Jh11mWraW2twAg44HgIjNtqWarUukuZXcxLZlkT63WNp/1HiqTMFPBb9/woMgbPaiAiPIp6G2mRqQJtfRjlkCe6/AM6Ok=,iv:97mtTdL2laravcvV5JuoIi/HkQKgcNgD9KXyfSmtUqo=,tag:WOaiCDwTikrlrjMdU7008g==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
