apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - coredns-configmap.yaml
  - coredns-serviceaccount.yaml
  - coredns-clusterrole.yaml
  - coredns-clusterrolebinding.yaml
  - coredns-deployment.yaml
  - coredns-service.yaml
