apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: contact-gateway
  namespace: contact
spec:
  gatewayClassName: traefik
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    hostname: kontakt.norsemen.io
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: letsencrypt-tls
