apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: contact-route
  namespace: contact
spec:
  hostnames:
  - kontakt.norsemen.io
  parentRefs:
  - name: contact-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: contact-service
      port: 8066
