apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kontakt-norsemen-io
  namespace: contact
spec:
  secretName: letsencrypt-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
  - kontakt.norsemen.io
