apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: contact
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:n8F0y097vyfUf8WUkOegygWQGiKwlCL64irMXE65hsnpRf+HtCxIBEelsAjKmdeHWn4przk0xsTD9PB0N/cQ9Syq4cqoo0MM56o3+RJK3xmq5AQAbYpTeBmARO32PYIWGWyaAp8PRPDk4/+vjo1vM5WC1K9AMRpU4LZgWO3MRDR/mJCM2EIyZdDBjYIMDcGXZb/2TYtTNc6k/pVH/k11VdFOmPLWKRqF6bHS,iv:DtvmPCj94dzXjHeTWDa7F466aOPUK7lUXzahV90ZsE8=,tag:Vs1iWHdRfzGO96yZelN0NQ==,type:str]
sops:
    age:
        - recipient: age19fmyfyqqx37raywwtlt7ynpgq7jd8dq365m79lqe7u8jy7e8kqesk0tzrp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBScjZNYXRCK0JsL1ErWm9p
            SG84Nngxbk5hS00rSE9jQi9paGZGUDFGM1N3Ckw1QUlOam5xaTBPQ0xtRkVCcmVE
            dEwrcW9yenkwVGwvUFdRamRyanhOZlkKLS0tIDIxNjJNNUdsTDYyYmJnejczY1I1
            akdlbXZLaExEcDU1QVg3WXhxV2Z4YUkKaXNr82RkOwBYuZBt0qwgcXlVt79mZyDL
            Oy0lgNj/psi0rfrEDm/Ef9kWgXPi4DFbD8v7sqfkLtbKib8EH4ciFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T15:08:34Z"
    mac: ENC[AES256_GCM,data:J8LWVO4jN4yGKUBRGL2bnkXDCcQtsQod474gW/hTFVCBCaUFnWSZzJCrd4iQhByGc0rI7N3Gb25axyF9raNdkbzi+DI8Qw3mIMD3yi29kVP4dY9+Px2KDcnV4JK1c21u2aRNLSZkawS9arz9H/zvTg6P8oII/O0QsWw5YM0L9Ao=,iv:IdW5FIKphC/s7t1r2hnbA0LdUII3Ufa/jtv8Eb02+z0=,tag:zONHBmbYVAMN0oCW7Tk+EA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
