apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - contact-service-secret.yaml
  - contact-service.yaml
  - contact-certificate.yaml
  - contact-gateway.yaml
  - contact-httproute.yaml
