# Infrastructure components kustomization
# Lists all infrastructure subfolders

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nginx-ingress
  - cert-manager
  - flux-system-secrets
