# k8s/apps/home/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: []
  # - ./example-app/deployment.yaml

commonLabels:
  app.kubernetes.io/managed-by: flux
