#ENC[AES256_GCM,data:JTH7YSVCSiTP6fMekFx73Q==,iv:OmSC/Py9obitIRFRmlQy1lFbldsiL8HIhOSiZ+zv3R4=,tag:BniE5hV/DDCI8Le2SJd8/A==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:WBKLJAQNx01BDpFJkgP2iDr8vFiK6lOqmjy2LjxFj0fJ5VBE4uHYKOsXMxDlha64vQMls9qwmjPeVq/DVGcmfWMrYZEduzc=,iv:QjNRlnzQH6L6YeQtg76P+8p52tqQYZKwpavo2gwb/tk=,tag:oR+3SQpbLKnjXCr0TFpr1g==,type:comment]
    #ENC[AES256_GCM,data:XTjicQKlCAjkJnYBVG4xd+KurkGdTJhzitvNIcYlmqHqhzQQQ9erk5zaT+tZi8Uc7dCfHHJjX0w=,iv:mNI/BulhTu4YBd67POnLFJFuM77IThdgMigI4n8B88o=,tag:StrFdhC9wBPtmJqtmfr8Qw==,type:comment]
    age.key: ENC[AES256_GCM,data:Y2RJ3PMLX+PaO9wbkcn47mE/zQzS+9vmZOHWnxqXW271sEy9p2l+5etou+V7rB+EeVhj494m3Ebsk6BIcDo8m9wvt+gY9beg0O9T/xc7bbTdx80GyV/ooguscuZpKDBslcUfG3KK9BIDCcKN2zagWyGjCafINBYiaClYdeEDl3MSU6bjlq1bgPvyM3mIhvOWprtNrTU+UAniO5WZFgCRoMyKCRztXbatkn++rp4DCY92znepgLKMpG+mpWY12ebN9rhgroLjAMFlMv76FU/7FDMyXmqeJnbZSoX+tW/fhe2mUNhfDCc6CzQnUl0svClZsDJ2bf9agxkHs1pi,iv:1F4m6VpVwy2YTLoluiWWb2XuI91DXGdqL3nupfP+jj0=,tag:mqv6pidc84jwljec1sZDiA==,type:str]
sops:
    age:
        - recipient: age19fmyfyqqx37raywwtlt7ynpgq7jd8dq365m79lqe7u8jy7e8kqesk0tzrp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUUJzUnNtYXo4UjFWb0Vy
            UDFiZU1LRUN3L3ZDNGpIRU1zV3IrSXk3SHpJClArc0RRVGZwMTllREN6bkdIcFhH
            OUwzVUVKdmowRHpLdGU2amdLWHBxRTAKLS0tIE4xK0ZLcnpuKzl4YVM2RWdCdW4x
            NVI4czM0dkNjWWYzOFhUYm13RUlaWE0KaOoDFFOZrf8BQmMqXBboHfMT6jAez4eH
            B4ERusWER39OaJpAlrxggHku0I3QtvxWcKQEDy1DxtkJfWme8OA2Nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-07T19:12:31Z"
    mac: ENC[AES256_GCM,data:IMt8i76sdjQ/PKSqKcCylzMxUXiYuELfeIidEWftgOijs+WVcBZnK7EehUBFV6sHd3rspAB9fahFpubaQAbfWsodklpPnvUMn9tLiI26U90OXDHkxXbuxFzMkMg4zpH+VuFUd1laDtHao2JoprIXGHUYTiBC+WXpo4zCoQ+F+U8=,iv:wpdBsqkqoKjbpneVgRUuPfIRkQuE+WJX7yFBYaYzn8U=,tag:iQ10K1INdzzXkP5w8TCZWw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
