apiVersion: v1
kind: Secret
metadata:
    name: flux-repo-secret
    namespace: flux-system
data:
    password: ENC[AES256_GCM,data:gfMDtJCIU/CfH4eXi1s/3wki/5N1aXX8tNI34cpT1KTBjKke5xeSGaaH9qLqTBkBgZt72zaF0Uc=,iv:7thjcjr6K3SlQJiMlRirqMriYx2TWQE2zLaLUSOMGrs=,tag:cgtJ4v/BNhqV3eLV6il44Q==,type:str]
type: Opaque
sops:
    age:
        - recipient: age19fmyfyqqx37raywwtlt7ynpgq7jd8dq365m79lqe7u8jy7e8kqesk0tzrp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmTllDdE9ZRGRXUmFBZGFs
            eGlSWjg4T2VjTEkvNnJ0N3NiWlZka21telR3ClVVelphekdVb050MkU5NFRSMnF0
            dFc1ZXRnMndtN1JOamJCOEtaR1hWZk0KLS0tIGVkY2ZvdjQwUVQ4TjZ3Tkcway9j
            QVl5MlpJeTI0SlZHT2x0WVJIRmpUa0UKewnN0slgYN+WLjQLj41j3w38rqjGJYSk
            fgsRy5jg9sAJzEEE9PSdFBrx9zj81EQKNLqctC1gZTxB+yu1ZtKzfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-07T19:13:00Z"
    mac: ENC[AES256_GCM,data:KBN1Khu3no5kF4aqXShPlPW41gr03JO/1vhYSC181b/N6gl2JJm1bj+PV66S63RgyKMoFaiSD1lVsVGPFcHVooiU8r6JYpzuzBuU/Lt4/a1s+F0Z/VqftizUpypBmP8IGMyBMlyCuMiILw7IWqTixsV5CfNE3+Wk5vIFXYm1J48=,iv:uqXLVYHJs9W61/KOcQVvM06zxkUCHY8pXBR1kWnnKGo=,tag:ceyoJ+gUK1iiDBpWpHIJbA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
