# k8s/infrastructure/secrets/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# The files inside this directory that Flux should apply.
# This is where your ENCRYPTED secrets will go.
resources:
  - age-secret.yaml 
  # This secret holds the private key for the SOPS controller.
  - github-pat-secret.yaml 
  # This secret holds the repository credentials.
