apiVersion: v1
kind: Secret
metadata:
    name: schmidtsgarage-github-token
    namespace: schmidtsgarage
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:C37fAxTRWXuSDkNg5mMDLnsZ+NSNOdN0zv639l2Uh6wTnkYEaPlXQsFlwcCgz+3PpnpT/5hFmj02m0QDhUg7FvoNABY3wW0/85+/LDPEanD9WoSweiAPsvDwuSUY,iv:1B3mL6ahltTyy4fS9TIZ2cq/OyUzeYIO3lVNaCIUN+o=,tag:5mzH+sBCT1sdb1kDlchhRA==,type:str]
sops:
    age:
        - recipient: age19fmyfyqqx37raywwtlt7ynpgq7jd8dq365m79lqe7u8jy7e8kqesk0tzrp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvYklvNTJvbTJLZDJhTWha
            ZmdyT0gxMEFmTGYzNzBQQjNONWxQbm9CNGdBCnJhUk5TTVhlNUZmMkhhSkdFWXNv
            WlQyU0NIa1oyRXFkeVE1M3phbjFibEkKLS0tIGJZM3A3MENWMnlxUzBQSEZ3dXNQ
            bm52ZWd1Rm93MUtpNVExVTlsQjZpTnMKqpRrdCg9nWmhlC5nJLF5X5UeCroRKgpM
            l6/hsw+hf6KvwkdSUTtgUyIIvNY2eBacXqcGw1XCp8z3/Nb7/zmsLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T13:59:49Z"
    mac: ENC[AES256_GCM,data:Q+1w8oKlXtA0BnHtTXKtzVC0OSSfTqeplVvMZoQWqqKn6aoQ8sP6p3RoDlwZupc4+ysZ96U2zdSR/vL/FaA0fseFsggDhdfpEH19mCOGV56oTRf5EImtUuWzmoRuQuMdiGOkex7JthkcTAr0zrL2HTUbwy/8IecsrpMaHIzTVv8=,iv:294usCQFSVywMvjUemi/TR4hsnB0qhB4hkCitdeA1tY=,tag:Jm9RloAFoY2Pvfk/Zae5YQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
