apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: contact
  namespace: envoy-gateway-system
spec:
  gatewayRef:
    name: contact-gateway
    namespace: contact
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: NodePort
        externalTrafficPolicy: Local
        patch:
          value:
            spec:
              ports:
                - name: https
                  port: 443
                  protocol: TCP
                  nodePort: 30444
      envoyDeployment:
        pod:
          nodeSelector:
            kubernetes.io/hostname: mothership
