apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: default
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      service:
        type: NodePort
        nodePorts:
          http: 30080
          https: 30443
      deployment:
        nodeSelector:
          kubernetes.io/hostname: mothership
