apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: envoy-gateway
      version: ">=1.6.0"
      sourceRef:
        kind: HelmRepository
        name: envoy-gateway
        namespace: envoy-gateway-system
  values:
    # Install CRDs and controller
    deployOperator: true
    installCRDs: true
