# k8s/infrastructure/secrets/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# List SOPS-encrypted secrets here as they are added.
# Use `make add-secret` to automatically append new entries.
resources:
  - ./szigethy-lan-tls.sops.yaml

