apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: contact
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:Y4myNONbfThGpOMVKkTVjdNrY8cGI8xIrPUDtOax7OR5Yf+6gkPs3hHyC3KJAyVDBQdlLr60J48FYi0M7/WkoGAbVHbk36N3z5TGXgGEZj18bN/jZG+7UKhV5btjgpVb4zU=,iv:XV2Z0t7NKFe/rFNSZ6Q6EtWh7sVtrc4xh6AheNspG8o=,tag:7y356DpdzsZFIqj7E45nLQ==,type:str]
sops:
    age:
        - recipient: age19fmyfyqqx37raywwtlt7ynpgq7jd8dq365m79lqe7u8jy7e8kqesk0tzrp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvenB0d3VVOFdMU29XYUZh
            dWpGRWtlbW1jWENSQWpKVUMzakExVGhCZGdFCm5OUVU0RUZJci9pbG1qeWVBcjU2
            V1ZlL245SkUxM2dKL2RFYU1QVjdiVEkKLS0tIEFZVzNpMWc2YXpFNFhTMWtUcGRE
            LzhzU1BmYkxQK1FmT2VrWGZSVnEvMTAKLKKI6VpKBsLWLv4X5djAPa04V3QoP38v
            B5hK2q54AZ36xKViAf8XPrcXIf9nzB7Cr6e0chYZGqWw/Z2YceE04g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T00:02:39Z"
    mac: ENC[AES256_GCM,data:iOHAVpHilA79gqK1e2YQ29ym2CmDU+5VwBa0jG/+0iB9CYpYo+Vxa/G+kWpZ1efCIoj7gzPyOW5HM0uYmFM26/f4avqCNzzPxOt4P+ypmwSthxs6t1nDAJeZZf6+NaWwq0OhTkWLXvVpD/NN+POGdL8ZH6AEX9LcBGCoFujlKfA=,iv:YDvRDXoRTjUaymHpMZN5ct5OKzTx5XowpyUF9wOYQzk=,tag:WBBQ5Q4guUvhDQS7ANx89A==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
