apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: contact
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:XeulPIHQsYUFqFGEElg9J3jMLelpy2mD2Kb1AxsLYnLZp1UdzvCWG4lqEwUU0GrbXvbcdYt6Ml8dPAlTO7fQ+F8XgKiJEEdzEJ2CamZsQo3DiaOa9cgXC6AgntQfKxslqKw=,iv:XzQdGbeNfS3q6ORfhTpUam9MS/o9HIAU7KPoAqcWusU=,tag:PqVQ5snyl+ezShsuUr5bMQ==,type:str]
sops:
    age:
        - recipient: age19fmyfyqqx37raywwtlt7ynpgq7jd8dq365m79lqe7u8jy7e8kqesk0tzrp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlN3FzcmZnT0txbVptYkVO
            cmNnU3VMamg0TWlkTTBJN2lmbHlqcUM2RURRCnJsV0dkVU15bS9qMHlIeGMxeGRi
            Um5qVFBPTlNyKzlIS0RiaWszeXBBM2sKLS0tIGlqRVFRT240NXdsVDZEUVFmV2JL
            d3hLd2g4REY3VmJ4d2JiNWxtOGx4U1kKCNTk+Uwp3wvQ72zlb3NClcybuMWBun8C
            IiL8BTR8AMrC9AyNQZoSFD0AQpddU12NLHIaciIFDJ3OZgEMF9/5DQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T00:13:20Z"
    mac: ENC[AES256_GCM,data:8LSDH+BcGegzwmsEVLxWjFchtVAh0Z6VMXzm+CBaO5v1Eh90lgIo3gfhPtA9pUnkDhwcBviH+gtcD1/S4ZIIEm7i3K5fpUKOyaKrnQlywPwKMhvLUsthx45frDZPjkvw1AxF+6AX1Pj+Uvx7uDpyR+Ef1+5Rch46ZP8hQjGrdpE=,iv:+FmqQWeNTUvw7xCeDQ+Q9RXIAEBwvx9xJKSmHG3iSs0=,tag:4JkktzkENMEeJSGB8HZbOQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
