apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: contact
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:3PaOY9/MUbBAmPUHROtIdPf8dfEy1qc2uxrWT1Im9mRGtitBmwLNW1oG198rPRzxT9DJZPQFp56fzH7qan2cpmoHpVvUn/PTD/sZmLBIgwBIC3dcIYXFWAFTiZdNtjtfOBM=,iv:21mdrrTH8WoYPod5KfNWYdHcj3ygU70BGsi+I4E6AzQ=,tag:MpQuX1qiIDS/OGBbSZvhRQ==,type:str]
sops:
    age:
        - recipient: age19fmyfyqqx37raywwtlt7ynpgq7jd8dq365m79lqe7u8jy7e8kqesk0tzrp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Mk1Rbm1xQThmZ2N5Q1M4
            U3JWdFJQWTJQTVdDU1VZd0xiR25sRFlGV2dvCjJqamxNNUtUNmNRU3ZFZXZNMWJm
            SlN2ZlF5aFA4ZFd6YWVTcmpZOWJZR28KLS0tIHJKaEVlQTJPbi9ZNSsvOU45NFlE
            UTZ0R2xIVE1ZTklKMjZJMHNnemg5N00KxZ5da7jsKE8mwSWOTxeQ+ezriNM2vIe0
            XeeecvAqxXFCacAgEDPVoSW01jclYd1we7YV8qGq8qaGE3URQDJLOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T00:06:21Z"
    mac: ENC[AES256_GCM,data:pu8L687HG9pQ6CUVsJ0nxrwKIf2b0Nl2v9KmXRTcIgnkqZbAhu5D1AW6m8pA/vr+pnfg39jEmHRmILhdmfSG13Zqq+MEMNNdZdjfRDU19ge2aE9D5k/qNpFSwDmqDhUJfsMNByHXjJpFZwYBGZmBhoGPB3ufLgXHGv5FFO/l+wc=,iv:yjRSHvMfpiiTS62vU1KoEun+OjSURifHoPZTIHeTLxw=,tag:WIwkapkoBWc7+yfqCJ0DVw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
