apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helloworld-www
  namespace: helloworld
spec:
  storageClassName: zfs-fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
