# Applications kustomization
# Add your app manifests here

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - schmidtsgarage.yaml
  - schmidtsgarage-pvc.yaml
  - schmidtsgarage-pat.sops.yaml
  # - myapp.yaml
  # - another-app.yaml
