apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: schmidtsgarage-www
  namespace: schmidtsgarage
spec:
  storageClassName: zfs-fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
