apiVersion: v1
kind: Secret
metadata:
    name: teknik-github-token
    namespace: teknik
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:bCRFBBykpxKmpzgIG2zOnn3bW9t4AFbjqiZzj4HNUZQocrgafVkdhCHHxBWhPp2vJ1TO/If2dahOgrJJY7rpotDejnONDth3rCuvpDbqdbE5szx/rgar/5kjvPZJ,iv:tTfsQ9tf8zZWfEklji+zjukpphrcV/pp53RZS2GENx8=,tag:XCxgeFveSE02jI9nGeE8mw==,type:str]
sops:
    age:
        - recipient: age19fmyfyqqx37raywwtlt7ynpgq7jd8dq365m79lqe7u8jy7e8kqesk0tzrp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Z2s3M3pqYlF5dXFJNnNG
            K1R5dTkvbHZpU3MyMjFnMGdkZEJvUi9lbFY0CjFWQUl3SEpNMmVNcWptUFNWQ2ly
            MENTcHd0MG5QU1BsaVZGcGRNUitXQ1kKLS0tIFJQTHVkY2lDa24rd1pBZDkxMUtC
            QWMzNVVkR0M2UGZ1VFYyNDllVWlUZDgKirC9sXry9AzkKkQLgtT+z5+mHWWxTCtk
            PRSBe8+XdY1XA9387xVojHvpnr7DQL54+YtxOa8dSf/jTyyClDAk5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T21:37:48Z"
    mac: ENC[AES256_GCM,data:7VYYlqkLtrP+W2DpntR6LBO+LHFkxtEzSuswgWrpdVe/RQ7YwgEf6+ImD/ZrmP9dWlfintAEJzS6NaUOOtDeywT6KnSlbL1YkiryixgqNfCKzTqmg3jDtVpSLtGTH3edjhLq4zKiw5eGbzYjBZVAuLa4xSgCDUTBpaNuNzsGF74=,iv:IXYFp72xw0gVLeUhUrdrJtTuU/DBftIL/geInqYqgsk=,tag:z/RkqWWl48QI+LTh24PV8w==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
