apiVersion: v1
kind: Secret
metadata:
    name: schmidtsgarage-github-token
    namespace: schmidtsgarage
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:j5pNEmb/l//RH/H92UsqMm7QzV2XAcRoo5jxsC+oYu8q2SzD2W19tuwXFE0VBvkke7A1KJcTI7W3nXuw5clSKXhGtrHhy5Le10zIv6P88iT3D5O9gpGsIlQmDuLd,iv:5bZJXwfAdLayH8rBWHnhbTJztRPFOJZf5V7j8Qt667k=,tag:8PwHfuxi5uOv/FZ8FE4ocQ==,type:str]
sops:
    age:
        - recipient: age19fmyfyqqx37raywwtlt7ynpgq7jd8dq365m79lqe7u8jy7e8kqesk0tzrp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTk1kZkw1eTJZSlN6STNM
            blBBYjNBK2Q0VTJ0cGFpck5IdkZFbW9Eb1ZrCjAyOVhVVEcxaS92bDY4UXRKNXBK
            eS9oTU55UUlESmxEcmVKeXJRTmEvV0EKLS0tIHhOVFpoRU4zSEhpZzFpeFA0TllH
            Y2t4dVhLWlA3ZmRwRnc2OVlsNFppNEUKf903CHEyaN3oCXhB5b+0m8THaTVBaMdf
            HNrqrke+TJzE+xincyG1om02mcwzU819Tpd8wihvmDtxzOVMfd2bQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T09:21:30Z"
    mac: ENC[AES256_GCM,data:Mg91p0K8vIVZYZYmyz8cJng12i0UYKxgCLAJzDykHrOBXsXgs4l45/+3iAQjAyqmw2mgo8s/502YNuRx4gNsXOW/gbvc4JtP/4huSPAyJj0HkPHboihJuSy/ty0uPws/+HOd6/HZ4C6TjR4WoZdBAw25L1V5RcHGKILQAaF+3Jg=,iv:JNERAzs5L0iFVazGMV9Q3ojErEHu9UWZefh4P16V5a0=,tag:vKbLEmQU8iL4IdTmxNvF9w==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
