apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway-proxy
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/clusters/home/envoy-gateway-proxy
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
  - name: envoy-gateway