apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../infrastructure/zfs-csi.yaml
  - ../../infrastructure/coredns.yaml
  - ../../infrastructure/cert-manager.yaml
  - ../../infrastructure/envoy-gateway.yaml
  - ../../infrastructure/envoy-gateway-proxy.yaml
  - ../../secrets
  - ../../apps