apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - storageclass_all.yaml
  - ../../infrastructure
  - ../../infrastructure/envoy-gateway-proxy
  - ../../apps
  - cert-manager-issuers-ks.yaml
  - flux-system
