apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - zfs-ks.yaml
  - coredns-ks.yaml
  - cert-manager-ks.yaml
  - envoy-gateway-ks.yaml
  - envoy-gateway-proxy-ks.yaml
  - secrets-ks.yaml
  - apps-ks.yaml