# clusters/home/kustomization.yaml
# Cluster-specific configuration
# This is the Flux entry point

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - storageclass_all.yaml
  - ../../apps
  - ../../infrastructure
  - cert-manager-issuers-ks.yaml
  - flux-system
