apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: zfs-csi
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/clusters/home/zfs
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system