# flux-system-secrets kustomization
# List SOPS-encrypted secrets here as they are added.
# Use `make add-secret` to automatically append new entries.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: []
